### ISSUE TITLE
Have a module to save output direct?

### ISSUE THREAD

**Issue by popeyaho001** [newfies-dialer/python-mstranslate#7]
As gTTS google TTS, is there have a module to save output direct?
Thank you so much!

**Comment by popeyaho** [comment]
I mean do some thing like that:
`mp3_fp = BytesIO()
    tts = gTTS(text, lang)
    tts.write_to_fp(mp3_fp)
    mp3_fp.seek(0)`
save to temp file?
as gTTS, they have `tts.write_to_fp()`
